# Generated by Django 2.2.12 on 2020-05-21 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_youngerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_to', to='accounts.Younger')),
            ],
        ),
    ]
