# Generated by Django 2.2.12 on 2020-05-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200522_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='elderapproval',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='accounts.Elder'),
        ),
    ]
