# Generated by Django 2.2.12 on 2020-05-26 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_elderapproval_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='elder',
            name='funds',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(default=django.utils.timezone.now)),
                ('care_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Younger')),
                ('care_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Elder')),
            ],
        ),
    ]
