# Generated by Django 2.2.12 on 2020-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200528_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_elder_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_younger_profile',
            field=models.BooleanField(default=False),
        ),
    ]
