# Generated by Django 2.2.12 on 2020-05-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200528_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_filled',
            field=models.BooleanField(default=False, verbose_name='I accept that the above given information is True'),
        ),
    ]
