# Generated by Django 2.2.12 on 2020-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_is_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_filled',
            field=models.BooleanField(verbose_name='I accept that the above given information is True'),
        ),
    ]
