# Generated by Django 2.2.12 on 2020-06-27 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200528_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('care_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Younger')),
                ('care_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Elder')),
            ],
        ),
    ]
