# Generated by Django 2.2.12 on 2020-06-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200627_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='younger',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
    ]
