# Generated by Django 2.2.12 on 2020-07-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_completed_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount_to_pay',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
