# Generated by Django 2.2.12 on 2020-07-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_transactions_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
