# Generated by Django 2.2.12 on 2020-07-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_transactions_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='scheduled_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
