# Generated by Django 2.2.12 on 2020-07-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200729_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_filled',
            field=models.BooleanField(blank=True, null=True, verbose_name='I accept that the above given information is True'),
        ),
    ]
